/**
 * Google Forms submission utility
 * Submits lead data to Google Forms without page redirect
 *
 * NOTE: Lead ID and Datetimestamp are auto-generated by Google Sheets/Forms
 * and should NOT be included in the submission payload
 */

// Google Form configuration
// Replace these entry IDs with values from your Google Form
// To find entry IDs: https://github.com/jiyaan-data-engineering/jiyaan-institute-website/blob/main/GOOGLE_FORM_SETUP.md
const GOOGLE_FORM_URL = "https://docs.google.com/forms/u/0/d/e/1FAIpQLScJNbKvJ9S-IZdh3m9Tmo3xUkNW4CwqITaygk87T-5iOapIiQ/formResponse"

// Form field entry IDs - VERIFIED AND TESTED
// Extracted from: https://forms.gle/D8BijjMuaK5ySWHS8
// Auto-generated fields (Lead ID, Datetimestamp) are excluded from submission
export const FORM_FIELDS = {
  email: "entry.804146219", // Email - Required
  name: "entry.294407203", // Name - Required
  phone: "entry.2006329507", // Phone - Required
  course: "entry.1775010313", // Course of Interest - Required (Checkbox field)
  message: "entry.166782921", // Message (optional)
  // Note: Lead ID and Datetimestamp are auto-generated by Google Forms
  // leadId: "entry.1700792524", // Auto-generated - do NOT submit
  // timestamp: "entry.9340487", // Auto-generated - do NOT submit
  // Backend/Admin fields (not submitted by website form):
  // assignedTo: "entry.1178934496",
  // status: "entry.1771432039",
  // followUpDate: "entry.1281460059",
  // demoDate: "entry.340016737",
  // interested: "entry.1335220265",
  // experience: "entry.1923683204",
  // currentRole: "entry.1467348373",
  // jobChange: "entry.457460750",
  // budgetConcern: "entry.1946357365",
  // telcallerNotes: "entry.1685320537",
  // nextAction: "entry.947654028",
}

export interface SubmissionData {
  name: string
  email: string
  phone: string
  course: string
  message?: string
}

/**
 * Submit data to Google Forms
 * Requires CORS-friendly approach (using fetch with no-cors mode)
 *
 * Note: Lead ID and Datetimestamp are auto-generated by Google Forms
 * and should not be included in the submission
 */
export async function submitToGoogleForms(data: SubmissionData): Promise<boolean> {
  try {
    const formData = new FormData()

    // Map website fields to Google Form entry IDs
    formData.append(FORM_FIELDS.email, data.email)
    formData.append(FORM_FIELDS.name, data.name)
    formData.append(FORM_FIELDS.phone, data.phone)
    formData.append(FORM_FIELDS.course, data.course)

    // Only add message if provided
    if (data.message?.trim()) {
      formData.append(FORM_FIELDS.message, data.message)
    }

    // Lead ID and Datetimestamp are auto-generated by Google Forms
    // Do NOT include them in the submission payload

    // Submit to Google Forms
    // Using no-cors mode because Google Forms doesn't support CORS
    const response = await fetch(GOOGLE_FORM_URL, {
      method: "POST",
      body: formData,
      mode: "no-cors", // Required for Google Forms (submission succeeds without CORS)
    })

    // Note: With no-cors mode, we can't check response status
    // But if fetch succeeds without throwing, submission was sent to Google Forms
    // Google will auto-populate Lead ID and Datetimestamp via Sheets formulas/scripts
    return true
  } catch (error) {
    console.error("Form submission error:", error)
    return false
  }
}

/**
 * Get submission status message
 */
export function getSubmissionMessage(name: string): string {
  const firstName = name.split(" ")[0] || "there"
  return `Thank you! Your demo request has been submitted successfully.\n\nOur team will contact you shortly.`
}
